import assert from 'node:assert/strict';
import { useCutsceneQueue } from '../src/hooks/useCutsceneQueue';
const store = useCutsceneQueue;
store.setState({ queue: [], presenter: null });
store.getState().acquirePresentation('decision');
store.getState().enqueue({ id: 'milestone', type: 'story_cinematic', payload: {} });
store.getState().acquirePresentation('cinematic');
assert.equal(store.getState().presenter, 'decision', 'queued milestone cannot interrupt choice/outcome');
store.getState().releasePresentation('unmounted-other-modal');
assert.equal(store.getState().presenter, 'decision', 'unrelated cleanup cannot release visible story');
store.getState().releasePresentation('decision');
store.getState().acquirePresentation('cinematic');
assert.equal(store.getState().presenter, 'cinematic');
assert.equal(store.getState().queue[0].id, 'milestone', 'waiting preserves queued payload');
store.getState().acquirePresentation('new-decision');
assert.equal(store.getState().presenter, 'cinematic', 'new decision waits for playing cinematic');
store.getState().dequeue();
store.getState().releasePresentation('cinematic');
store.getState().acquirePresentation('new-decision');
assert.equal(store.getState().presenter, 'new-decision');
store.setState({ queue: [], presenter: null });
console.log('story presentation ownership passed');
