// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://skskoodqidiegweuhrel.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNrc2tvb2RxaWRpZWd3ZXVocmVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzNjE5NjcsImV4cCI6MjA2MzkzNzk2N30.8-uYzjDeDdowAnzjjZkYQN7Xai2hwCvYgtK_mxYp9X0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);