/**
 * City-flavoured Studio Event Director rows (home city, career start).
 *
 * One local beat per city, each gated on `facts.cityId`, so they only ever appear in that city and
 * never on legacy saves. Same contract as the rest of the pool: typed, capped `DomainEffect`s only,
 * cooldowns, occurrence caps and a delegable safe default. Amounts are studio dollars.
 */
import type { StudioEventDefinition } from './eventDirector';

const opt = (o: StudioEventDefinition['options'][number]): StudioEventDefinition['options'][number] => o;

export const CITY_EVENTS: readonly StudioEventDefinition[] = [
  {
    id: 'la_label_dropin',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 60,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'los-angeles' && f.reputation >= 15,
    narrativeKey: 'city.la.label-dropin',
    kicker: 'LOS ANGELES // A&R IN THE LOBBY',
    title: 'An A&R Walks In Off Sunset',
    context: () => 'A label scout was in the building for another room and heard your monitors through the wall. They have twenty minutes and a business card.',
    options: [
      opt({ id: 'la_play_reel', label: 'Play them your best reel', flavorText: 'Twenty minutes, no second take.', effects: [{ kind: 'reputation', amount: 5 }, { kind: 'money', amount: 200 }], outcome: 'They leave a finder fee on the desk and a promise to call.' }),
      opt({ id: 'la_hold_slot', label: 'Keep the booking, offer a rain check', flavorText: 'Clients first.', effects: [{ kind: 'clientXp', amount: 12 }], outcome: 'Your client notices. The scout writes down the studio name anyway.' }),
    ],
    delegable: true,
    defaultOptionId: 'la_hold_slot',
  },
  {
    id: 'nashville_songwriter_round',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'nashville',
    narrativeKey: 'city.nashville.round',
    kicker: 'NASHVILLE // WRITERS IN THE ROUND',
    title: 'A Songwriters’ Round Needs a Room',
    context: () => 'Four writers want to demo a whole night of songs on a handshake and a tip jar. Whatever you charge, the songs will be good.',
    options: [
      opt({ id: 'nash_host', label: 'Host the round at cost', flavorText: 'Coffee, a few mics, no invoice.', effects: [{ kind: 'money', amount: -120 }, { kind: 'xp', amount: 40 }, { kind: 'reputation', amount: 4 }], outcome: 'By midnight there are three songs worth finishing and one you will hum for a week.' }),
      opt({ id: 'nash_book_paid', label: 'Book it as a paid half-day', flavorText: 'Fair rate, fair songs.', effects: [{ kind: 'money', amount: 260 }], outcome: 'They pay on the spot and promise to bring friends.' }),
    ],
    delegable: true,
    defaultOptionId: 'nash_book_paid',
  },
  {
    id: 'london_pirate_radio',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'london',
    narrativeKey: 'city.london.pirate-radio',
    kicker: 'LONDON // THE AERIAL ON THE ROOF',
    title: 'Pirate Radio Wants an Exclusive',
    context: () => 'A pirate station on the twelfth floor next door wants to play your latest session before anyone else has heard it. Quietly, of course.',
    options: [
      opt({ id: 'lon_give_it', label: 'Hand over the rough mix', flavorText: 'Buzz is currency.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'clientXp', amount: -6 }], outcome: 'The phones light up. Your client is flattered and a little annoyed.' }),
      opt({ id: 'lon_ask_client', label: 'Ask the client first', flavorText: 'Permission, then volume.', effects: [{ kind: 'clientXp', amount: 10 }, { kind: 'reputation', amount: 2 }], outcome: 'They say yes with a grin. A smaller splash, a bigger thank-you.' }),
    ],
    delegable: true,
    defaultOptionId: 'lon_ask_client',
  },
  {
    id: 'berlin_curfew_night',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'berlin',
    narrativeKey: 'city.berlin.curfew',
    kicker: 'BERLIN // THE NIGHT THAT DID NOT END',
    title: 'The Club Next Door Never Closed',
    context: () => 'The bass from the club next door has been leaking through your live room since midnight. A promoter pokes his head in: want to record the afterparty?',
    options: [
      opt({ id: 'ber_record_it', label: 'Roll tape on the afterparty', flavorText: 'Raw, loud, unrepeatable.', effects: [{ kind: 'money', amount: 220 }, { kind: 'gearCondition', amount: -4 }, { kind: 'xp', amount: 30 }], outcome: 'You get a hundred minutes of something nobody will ever be able to recreate.' }),
      opt({ id: 'ber_soundproof', label: 'Insist on a quiet night', flavorText: 'Pay the promoter in good faith.', effects: [{ kind: 'money', amount: -80 }, { kind: 'clientXp', amount: 8 }], outcome: 'The promoter respects it. The bass drops two floors down.' }),
    ],
    delegable: true,
    defaultOptionId: 'ber_soundproof',
  },
  {
    id: 'tokyo_city_pop_revival',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'tokyo',
    narrativeKey: 'city.tokyo.city-pop',
    kicker: 'TOKYO // THE VINYL BAR DOWNSTAIRS',
    title: 'A Reissue Label Wants Your Room',
    context: () => 'The owner of the vinyl bar downstairs is reissuing a forgotten record and wants it remastered through your gear. The tapes are in a shoebox.',
    options: [
      opt({ id: 'tok_remaster', label: 'Take the remaster job', flavorText: 'Patience, steady hands, no clipping.', effects: [{ kind: 'money', amount: 240 }, { kind: 'xp', amount: 35 }], outcome: 'The tapes sing. The owner bows lower than you expected.' }),
      opt({ id: 'tok_trade', label: 'Trade it for a rare fader set', flavorText: 'Gear for goodwill.', effects: [{ kind: 'gearCondition', amount: 8 }, { kind: 'reputation', amount: 3 }], outcome: 'Your console feels newer than it has in a decade.' }),
    ],
    delegable: true,
    defaultOptionId: 'tok_remaster',
  },
  {
    id: 'rio_carnival_rehearsal',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'rio',
    narrativeKey: 'city.rio.carnival',
    kicker: 'RIO // A HUNDRED DRUMS AT THE DOOR',
    title: 'A Samba School Brings the Whole Bateria',
    context: () => 'A samba school wants to record its carnival rehearsal in your room. It does not fit. They intend to make it fit.',
    options: [
      opt({ id: 'rio_full_band', label: 'Open every door and record it all', flavorText: 'Mic the street, mic the stairs.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'money', amount: 120 }, { kind: 'gearCondition', amount: -3 }], outcome: 'It is the loudest and best thing you have ever put to tape.' }),
      opt({ id: 'rio_small_group', label: 'Take the percussion section only', flavorText: 'Quality over crowd.', effects: [{ kind: 'money', amount: 180 }, { kind: 'xp', amount: 25 }], outcome: 'Clean, tight, danceable, and the drums still shake the glass.' }),
    ],
    delegable: true,
    defaultOptionId: 'rio_small_group',
  },
];

/** Two more local beats per city. Same rules: gated on the city, capped effects, safe delegable default. */
const local = (
  id: string, city: string, key: string, kicker: string, title: string, context: string,
  a: { id: string; label: string; flavorText: string; effects: StudioEventDefinition['options'][number]['effects']; outcome: string },
  b: { id: string; label: string; flavorText: string; effects: StudioEventDefinition['options'][number]['effects']; outcome: string },
  defaultOptionId: string,
  gate: (f: Parameters<StudioEventDefinition['eligible']>[0]) => boolean = () => true,
): StudioEventDefinition => ({
  id, family: 'city-local', baseWeight: 8, cooldownDays: 65, maxOccurrences: 2,
  eligible: (f) => f.cityId === city && gate(f),
  narrativeKey: `city.${key}`, kicker, title, context: () => context,
  options: [opt(a), opt(b)], delegable: true, defaultOptionId,
});

export const MORE_CITY_EVENTS: readonly StudioEventDefinition[] = [
  local('la_session_player_dropin', 'los-angeles', 'la.session-player', 'LOS ANGELES // A FAMOUS HAND', 'A Session Legend Needs a Room for an Hour',
    'A session guitarist who has played on half the records in your collection has an hour free and a cancelled booking across town.',
    { id: 'la_sp_pay', label: 'Pay their rate and record something', flavorText: 'One take, one hour.', effects: [{ kind: 'money', amount: -180 }, { kind: 'xp', amount: 45 }, { kind: 'reputation', amount: 3 }], outcome: 'You get a take nobody else in town can play.' },
    { id: 'la_sp_trade', label: 'Trade the hour for a favour', flavorText: 'They owe you one.', effects: [{ kind: 'clientXp', amount: 12 }, { kind: 'reputation', amount: 2 }], outcome: 'They shake your hand. The favour is noted in a very small book.' }, 'la_sp_trade'),
  local('la_heatwave_blackout', 'los-angeles', 'la.heatwave', 'LOS ANGELES // 41 DEGREES', 'The Heatwave Takes the Power',
    'A brownout rolls across the valley. The air conditioning dies, the racks start to cook and a nervous client sits in the live room.',
    { id: 'la_hw_generator', label: 'Rent a generator', flavorText: 'Loud, but safe.', effects: [{ kind: 'money', amount: -260 }, { kind: 'gearCondition', amount: 4 }], outcome: 'Everything survives. The client buys lunch.' },
    { id: 'la_hw_shut', label: 'Shut down and wait', flavorText: 'Cool the room, rebook the day.', effects: [{ kind: 'clientXp', amount: -6 }, { kind: 'gearCondition', amount: 2 }], outcome: 'Nothing breaks. Nothing gets recorded either.' }, 'la_hw_generator'),
  local('nashville_demo_wall', 'nashville', 'nashville.demo-wall', 'NASHVILLE // THE DEMO WALL', 'A Wall of Cassettes Falls Off the Shelf',
    'Someone leans on the shelf and a decade of unlabelled demos hits the floor. One of the tapes has a song you recognise from the radio.',
    { id: 'nash_dw_digitise', label: 'Digitise the whole wall', flavorText: 'A weekend of transfers.', effects: [{ kind: 'xp', amount: 55 }, { kind: 'reputation', amount: 3 }], outcome: 'You find three songs worth recording again.' },
    { id: 'nash_dw_sell', label: 'Sell the radio one to a publisher', flavorText: 'Quick money.', effects: [{ kind: 'money', amount: 300 }, { kind: 'reputation', amount: -2 }], outcome: 'The publisher is delighted. The writer is not.' }, 'nash_dw_digitise'),
  local('nashville_open_mic', 'nashville', 'nashville.open-mic', 'NASHVILLE // WEDNESDAY NIGHT', 'The Open Mic Down the Street Wants a Mixer',
    'The bar around the corner has a famous open mic and a broken board. The owner needs a mixer by seven.',
    { id: 'nash_om_volunteer', label: 'Volunteer for the night', flavorText: 'Fix the board, run the room.', effects: [{ kind: 'reputation', amount: 4 }, { kind: 'xp', amount: 30 }], outcome: 'You meet three writers and one future client.' },
    { id: 'nash_om_invoice', label: 'Send an invoice', flavorText: 'Fair work, fair pay.', effects: [{ kind: 'money', amount: 140 }], outcome: 'The owner pays on the nail and offers you a free pint.' }, 'nash_om_invoice'),
  local('london_tube_strike', 'london', 'london.tube-strike', 'LONDON // NO TRAINS', 'The Tube Strike Strands the Band',
    'Half your session is stuck on a platform in zone four. The other half is already in the live room, drinking tea.',
    { id: 'lon_ts_rework', label: 'Re-plan the day around who is here', flavorText: 'Start with the rhythm section.', effects: [{ kind: 'xp', amount: 35 }, { kind: 'clientXp', amount: 6 }], outcome: 'The day gets stranger and the record gets better.' },
    { id: 'lon_ts_cabs', label: 'Send cabs for the rest', flavorText: 'Pay for punctuality.', effects: [{ kind: 'money', amount: -140 }, { kind: 'clientXp', amount: 10 }], outcome: 'Everyone arrives annoyed. The take that follows is excellent.' }, 'lon_ts_rework'),
  local('london_music_press', 'london', 'london.press', "LONDON // NEXT WEEK'S COVER", 'A Writer from the Music Press Wants a Studio Visit',
    'A weekly music paper wants five hundred words on your room. They also want a quote about your favourite microphone.',
    { id: 'lon_mp_yes', label: 'Give them the full tour', flavorText: 'Honest, charming, slightly too long.', effects: [{ kind: 'reputation', amount: 5 }], outcome: 'The piece runs under a headline you did not choose.' },
    { id: 'lon_mp_polite', label: 'Politely decline', flavorText: 'Let the records talk.', effects: [{ kind: 'clientXp', amount: 6 }], outcome: 'Your clients like your discretion.' }, 'lon_mp_yes'),
  local('berlin_techno_loan', 'berlin', 'berlin.loan', 'BERLIN // A CABLE LOOM', 'The Club Wants to Borrow Your Speakers',
    'A club three streets over has blown a stack and the headliner lands at midnight. They offer to rent your monitors for a night.',
    { id: 'ber_tl_rent', label: 'Rent them out', flavorText: 'Make them a deal.', effects: [{ kind: 'money', amount: 240 }, { kind: 'gearCondition', amount: -5 }], outcome: 'They come back hot, bass-dusted and perfectly fine.' },
    { id: 'ber_tl_decline', label: 'Say no and keep the room quiet', flavorText: 'Your clients come first.', effects: [{ kind: 'clientXp', amount: 8 }], outcome: 'The promoter respects that and finds a loan elsewhere.' }, 'ber_tl_decline'),
  local('berlin_modular_swap', 'berlin', 'berlin.modular', 'BERLIN // THE RACK IN THE CORNER', 'A Modular Wizard Offers a Swap',
    'A local synth builder with silver rings and no sleep offers a patched-up voice module in exchange for a day of studio time.',
    { id: 'ber_ms_swap', label: 'Take the swap', flavorText: 'Time for sound.', effects: [{ kind: 'gearCondition', amount: 6 }, { kind: 'xp', amount: 40 }], outcome: 'Your studio has a new voice and a few new bruises on the patch bay.' },
    { id: 'ber_ms_cash', label: 'Rent them the room for cash', flavorText: 'Keep it simple.', effects: [{ kind: 'money', amount: 210 }], outcome: 'They bring their own cables and leave them behind.' }, 'ber_ms_cash'),
  local('tokyo_karaoke_night', 'tokyo', 'tokyo.karaoke', 'TOKYO // PRIVATE ROOM 7', 'A Label Throws a Karaoke Night',
    'A label is looking for a backing-track engineer and has booked you a seat at a very long table.',
    { id: 'tok_kn_sing', label: 'Sing one song', flavorText: 'Courage, not talent.', effects: [{ kind: 'reputation', amount: 4 }, { kind: 'clientXp', amount: 8 }], outcome: 'You are terrible. They love you for it.' },
    { id: 'tok_kn_pitch', label: 'Pitch the label instead', flavorText: 'Be the professional in the room.', effects: [{ kind: 'money', amount: 220 }], outcome: 'You leave with a contract and a very strange haircut photo.' }, 'tok_kn_pitch'),
  local('tokyo_earthquake_drill', 'tokyo', 'tokyo.drill', 'TOKYO // 3.2 ON THE SCALE', 'A Small Quake Shakes the Racks',
    'The racks sway and a rack-mount compressor slides a few millimetres off its ears. Nothing falls, but the whole room is thinking about it.',
    { id: 'tok_ed_secure', label: 'Strap down the racks', flavorText: 'Prepare properly.', effects: [{ kind: 'money', amount: -160 }, { kind: 'gearCondition', amount: 5 }], outcome: 'The racks are quiet and a lot more confident.' },
    { id: 'tok_ed_ignore', label: 'Carry on recording', flavorText: 'It was only a small one.', effects: [{ kind: 'gearCondition', amount: -5 }, { kind: 'xp', amount: 20 }], outcome: 'You get a great take and a cracked hinge.' }, 'tok_ed_secure'),
  local('rio_street_party', 'rio', 'rio.street-party', 'RIO // A BLOCK PARTY AT THE DOOR', 'The Street Party Wants Your Console',
    'A block party has set up speakers in the street. They would very much like to wheel your mixing desk out to the pavement.',
    { id: 'rio_sp_lend', label: 'Wheel it out', flavorText: 'Mics in the street, desk on the kerb.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'gearCondition', amount: -6 }], outcome: 'You record the best crowd you have ever heard. The desk smells of caipirinha.' },
    { id: 'rio_sp_mics', label: 'Send two mics and an engineer', flavorText: 'Compromise, with cables.', effects: [{ kind: 'reputation', amount: 3 }, { kind: 'money', amount: 120 }], outcome: 'You get a hundred friends and a clean multitrack.' }, 'rio_sp_mics'),
  local('rio_rainy_season', 'rio', 'rio.rain', 'RIO // THE RAINY SEASON', 'The Roof Starts Singing',
    'The tropical rain finds a hole in the live room roof and starts a rhythm of its own on the snare drum.',
    { id: 'rio_rs_repair', label: 'Patch the roof', flavorText: 'Buckets first, tiles after.', effects: [{ kind: 'money', amount: -200 }, { kind: 'gearCondition', amount: 3 }], outcome: 'Dry, tidy and a little sad.' },
    { id: 'rio_rs_record', label: 'Record the rain as an instrument', flavorText: 'Roll tape, close the window.', effects: [{ kind: 'xp', amount: 50 }, { kind: 'gearCondition', amount: -4 }], outcome: 'It ends up on three records and a ringtone.' }, 'rio_rs_repair'),
];
