/**
 * City-flavoured Studio Event Director rows (home city, career start).
 *
 * One local beat per city, each gated on `facts.cityId`, so they only ever appear in that city and
 * never on legacy saves. Same contract as the rest of the pool: typed, capped `DomainEffect`s only,
 * cooldowns, occurrence caps and a delegable safe default. Amounts are studio dollars.
 */
import type { StudioEventDefinition } from './eventDirector';

const opt = (o: StudioEventDefinition['options'][number]): StudioEventDefinition['options'][number] => o;

export const CITY_EVENTS: readonly StudioEventDefinition[] = [
  {
    id: 'la_label_dropin',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 60,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'los-angeles' && f.reputation >= 15,
    narrativeKey: 'city.la.label-dropin',
    kicker: 'LOS ANGELES // A&R IN THE LOBBY',
    title: 'An A&R Walks In Off Sunset',
    context: () => 'A label scout was in the building for another room and heard your monitors through the wall. They have twenty minutes and a business card.',
    options: [
      opt({ id: 'la_play_reel', label: 'Play them your best reel', flavorText: 'Twenty minutes, no second take.', effects: [{ kind: 'reputation', amount: 5 }, { kind: 'money', amount: 200 }], outcome: 'They leave a finder fee on the desk and a promise to call.' }),
      opt({ id: 'la_hold_slot', label: 'Keep the booking, offer a rain check', flavorText: 'Clients first.', effects: [{ kind: 'clientXp', amount: 12 }], outcome: 'Your client notices. The scout writes down the studio name anyway.' }),
    ],
    delegable: true,
    defaultOptionId: 'la_hold_slot',
  },
  {
    id: 'nashville_songwriter_round',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'nashville',
    narrativeKey: 'city.nashville.round',
    kicker: 'NASHVILLE // WRITERS IN THE ROUND',
    title: 'A Songwriters’ Round Needs a Room',
    context: () => 'Four writers want to demo a whole night of songs on a handshake and a tip jar. Whatever you charge, the songs will be good.',
    options: [
      opt({ id: 'nash_host', label: 'Host the round at cost', flavorText: 'Coffee, a few mics, no invoice.', effects: [{ kind: 'money', amount: -120 }, { kind: 'xp', amount: 40 }, { kind: 'reputation', amount: 4 }], outcome: 'By midnight there are three songs worth finishing and one you will hum for a week.' }),
      opt({ id: 'nash_book_paid', label: 'Book it as a paid half-day', flavorText: 'Fair rate, fair songs.', effects: [{ kind: 'money', amount: 260 }], outcome: 'They pay on the spot and promise to bring friends.' }),
    ],
    delegable: true,
    defaultOptionId: 'nash_book_paid',
  },
  {
    id: 'london_pirate_radio',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'london',
    narrativeKey: 'city.london.pirate-radio',
    kicker: 'LONDON // THE AERIAL ON THE ROOF',
    title: 'Pirate Radio Wants an Exclusive',
    context: () => 'A pirate station on the twelfth floor next door wants to play your latest session before anyone else has heard it. Quietly, of course.',
    options: [
      opt({ id: 'lon_give_it', label: 'Hand over the rough mix', flavorText: 'Buzz is currency.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'clientXp', amount: -6 }], outcome: 'The phones light up. Your client is flattered and a little annoyed.' }),
      opt({ id: 'lon_ask_client', label: 'Ask the client first', flavorText: 'Permission, then volume.', effects: [{ kind: 'clientXp', amount: 10 }, { kind: 'reputation', amount: 2 }], outcome: 'They say yes with a grin. A smaller splash, a bigger thank-you.' }),
    ],
    delegable: true,
    defaultOptionId: 'lon_ask_client',
  },
  {
    id: 'berlin_curfew_night',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'berlin',
    narrativeKey: 'city.berlin.curfew',
    kicker: 'BERLIN // THE NIGHT THAT DID NOT END',
    title: 'The Club Next Door Never Closed',
    context: () => 'The bass from the club next door has been leaking through your live room since midnight. A promoter pokes his head in: want to record the afterparty?',
    options: [
      opt({ id: 'ber_record_it', label: 'Roll tape on the afterparty', flavorText: 'Raw, loud, unrepeatable.', effects: [{ kind: 'money', amount: 220 }, { kind: 'gearCondition', amount: -4 }, { kind: 'xp', amount: 30 }], outcome: 'You get a hundred minutes of something nobody will ever be able to recreate.' }),
      opt({ id: 'ber_soundproof', label: 'Insist on a quiet night', flavorText: 'Pay the promoter in good faith.', effects: [{ kind: 'money', amount: -80 }, { kind: 'clientXp', amount: 8 }], outcome: 'The promoter respects it. The bass drops two floors down.' }),
    ],
    delegable: true,
    defaultOptionId: 'ber_soundproof',
  },
  {
    id: 'tokyo_city_pop_revival',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'tokyo',
    narrativeKey: 'city.tokyo.city-pop',
    kicker: 'TOKYO // THE VINYL BAR DOWNSTAIRS',
    title: 'A Reissue Label Wants Your Room',
    context: () => 'The owner of the vinyl bar downstairs is reissuing a forgotten record and wants it remastered through your gear. The tapes are in a shoebox.',
    options: [
      opt({ id: 'tok_remaster', label: 'Take the remaster job', flavorText: 'Patience, steady hands, no clipping.', effects: [{ kind: 'money', amount: 240 }, { kind: 'xp', amount: 35 }], outcome: 'The tapes sing. The owner bows lower than you expected.' }),
      opt({ id: 'tok_trade', label: 'Trade it for a rare fader set', flavorText: 'Gear for goodwill.', effects: [{ kind: 'gearCondition', amount: 8 }, { kind: 'reputation', amount: 3 }], outcome: 'Your console feels newer than it has in a decade.' }),
    ],
    delegable: true,
    defaultOptionId: 'tok_remaster',
  },
  {
    id: 'rio_carnival_rehearsal',
    family: 'city-local',
    baseWeight: 9,
    cooldownDays: 55,
    maxOccurrences: 3,
    eligible: (f) => f.cityId === 'rio',
    narrativeKey: 'city.rio.carnival',
    kicker: 'RIO // A HUNDRED DRUMS AT THE DOOR',
    title: 'A Samba School Brings the Whole Bateria',
    context: () => 'A samba school wants to record its carnival rehearsal in your room. It does not fit. They intend to make it fit.',
    options: [
      opt({ id: 'rio_full_band', label: 'Open every door and record it all', flavorText: 'Mic the street, mic the stairs.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'money', amount: 120 }, { kind: 'gearCondition', amount: -3 }], outcome: 'It is the loudest and best thing you have ever put to tape.' }),
      opt({ id: 'rio_small_group', label: 'Take the percussion section only', flavorText: 'Quality over crowd.', effects: [{ kind: 'money', amount: 180 }, { kind: 'xp', amount: 25 }], outcome: 'Clean, tight, danceable, and the drums still shake the glass.' }),
    ],
    delegable: true,
    defaultOptionId: 'rio_small_group',
  },
  {
    id: 'detroit_house_band_call',
    family: 'city-local', baseWeight: 9, cooldownDays: 55, maxOccurrences: 3,
    eligible: (f) => f.cityId === 'detroit', narrativeKey: 'city.detroit.house-band',
    kicker: 'DETROIT // THE RHYTHM SECTION IS READY', title: 'A House Band Has One Free Hour',
    context: () => 'A rhythm section arrives between label dates with one hour, a finished arrangement and the tightest pocket in town.',
    options: [
      opt({ id: 'det_roll_tape', label: 'Roll tape immediately', flavorText: 'No rehearsal needed.', effects: [{ kind: 'money', amount: -100 }, { kind: 'xp', amount: 40 }, { kind: 'reputation', amount: 4 }], outcome: 'The first take locks so hard the second feels unnecessary.' }),
      opt({ id: 'det_book_later', label: 'Book a proper paid date', flavorText: 'Give the session room to breathe.', effects: [{ kind: 'money', amount: 220 }, { kind: 'clientXp', amount: 6 }], outcome: 'They leave a deposit and the arrangement on your piano.' }),
    ],
    delegable: true, defaultOptionId: 'det_book_later',
  },
  {
    id: 'lagos_generator_session',
    family: 'city-local', baseWeight: 9, cooldownDays: 55, maxOccurrences: 3,
    eligible: (f) => f.cityId === 'lagos', narrativeKey: 'city.lagos.generator',
    kicker: 'LAGOS // THE LIGHTS GO OUT', title: 'The Generator Joins the Rhythm Section',
    context: () => 'Power drops halfway through a live take. The backup generator catches, humming almost exactly in key, and the band never stops.',
    options: [
      opt({ id: 'lag_keep_rolling', label: 'Keep rolling on backup power', flavorText: 'The groove survived; follow it.', effects: [{ kind: 'xp', amount: 40 }, { kind: 'reputation', amount: 4 }, { kind: 'gearCondition', amount: -3 }], outcome: 'The generator hum becomes part of the breakdown.' }),
      opt({ id: 'lag_reset', label: 'Reset and protect the equipment', flavorText: 'Clean power, fresh take.', effects: [{ kind: 'money', amount: -100 }, { kind: 'gearCondition', amount: 4 }], outcome: 'The next take is safer, cleaner and nearly as alive.' }),
    ],
    delegable: true, defaultOptionId: 'lag_reset',
  },
];

/** Two more local beats per city. Same rules: gated on the city, capped effects, safe delegable default. */
const local = (
  id: string, city: string, key: string, kicker: string, title: string, context: string,
  a: { id: string; label: string; flavorText: string; effects: StudioEventDefinition['options'][number]['effects']; outcome: string },
  b: { id: string; label: string; flavorText: string; effects: StudioEventDefinition['options'][number]['effects']; outcome: string },
  defaultOptionId: string,
  gate: (f: Parameters<StudioEventDefinition['eligible']>[0]) => boolean = () => true,
): StudioEventDefinition => ({
  id, family: 'city-local', baseWeight: 8, cooldownDays: 65, maxOccurrences: 2,
  eligible: (f) => f.cityId === city && gate(f),
  narrativeKey: `city.${key}`, kicker, title, context: () => context,
  options: [opt(a), opt(b)], delegable: true, defaultOptionId,
});

export const MORE_CITY_EVENTS: readonly StudioEventDefinition[] = [
  local('la_session_player_dropin', 'los-angeles', 'la.session-player', 'LOS ANGELES // A FAMOUS HAND', 'A Session Legend Needs a Room for an Hour',
    'A session guitarist who has played on half the records in your collection has an hour free and a cancelled booking across town.',
    { id: 'la_sp_pay', label: 'Pay their rate and record something', flavorText: 'One take, one hour.', effects: [{ kind: 'money', amount: -180 }, { kind: 'xp', amount: 45 }, { kind: 'reputation', amount: 3 }], outcome: 'You get a take nobody else in town can play.' },
    { id: 'la_sp_trade', label: 'Trade the hour for a favour', flavorText: 'They owe you one.', effects: [{ kind: 'clientXp', amount: 12 }, { kind: 'reputation', amount: 2 }], outcome: 'They shake your hand. The favour is noted in a very small book.' }, 'la_sp_trade'),
  local('la_heatwave_blackout', 'los-angeles', 'la.heatwave', 'LOS ANGELES // 41 DEGREES', 'The Heatwave Takes the Power',
    'A brownout rolls across the valley. The air conditioning dies, the racks start to cook and a nervous client sits in the live room.',
    { id: 'la_hw_generator', label: 'Rent a generator', flavorText: 'Loud, but safe.', effects: [{ kind: 'money', amount: -260 }, { kind: 'gearCondition', amount: 4 }], outcome: 'Everything survives. The client buys lunch.' },
    { id: 'la_hw_shut', label: 'Shut down and wait', flavorText: 'Cool the room, rebook the day.', effects: [{ kind: 'clientXp', amount: -6 }, { kind: 'gearCondition', amount: 2 }], outcome: 'Nothing breaks. Nothing gets recorded either.' }, 'la_hw_generator'),
  local('nashville_demo_wall', 'nashville', 'nashville.demo-wall', 'NASHVILLE // THE DEMO WALL', 'A Wall of Cassettes Falls Off the Shelf',
    'Someone leans on the shelf and a decade of unlabelled demos hits the floor. One of the tapes has a song you recognise from the radio.',
    { id: 'nash_dw_digitise', label: 'Digitise the whole wall', flavorText: 'A weekend of transfers.', effects: [{ kind: 'xp', amount: 55 }, { kind: 'reputation', amount: 3 }], outcome: 'You find three songs worth recording again.' },
    { id: 'nash_dw_sell', label: 'Sell the radio one to a publisher', flavorText: 'Quick money.', effects: [{ kind: 'money', amount: 300 }, { kind: 'reputation', amount: -2 }], outcome: 'The publisher is delighted. The writer is not.' }, 'nash_dw_digitise'),
  local('nashville_open_mic', 'nashville', 'nashville.open-mic', 'NASHVILLE // WEDNESDAY NIGHT', 'The Open Mic Down the Street Wants a Mixer',
    'The bar around the corner has a famous open mic and a broken board. The owner needs a mixer by seven.',
    { id: 'nash_om_volunteer', label: 'Volunteer for the night', flavorText: 'Fix the board, run the room.', effects: [{ kind: 'reputation', amount: 4 }, { kind: 'xp', amount: 30 }], outcome: 'You meet three writers and one future client.' },
    { id: 'nash_om_invoice', label: 'Send an invoice', flavorText: 'Fair work, fair pay.', effects: [{ kind: 'money', amount: 140 }], outcome: 'The owner pays on the nail and offers you a free pint.' }, 'nash_om_invoice'),
  local('london_tube_strike', 'london', 'london.tube-strike', 'LONDON // NO TRAINS', 'The Tube Strike Strands the Band',
    'Half your session is stuck on a platform in zone four. The other half is already in the live room, drinking tea.',
    { id: 'lon_ts_rework', label: 'Re-plan the day around who is here', flavorText: 'Start with the rhythm section.', effects: [{ kind: 'xp', amount: 35 }, { kind: 'clientXp', amount: 6 }], outcome: 'The day gets stranger and the record gets better.' },
    { id: 'lon_ts_cabs', label: 'Send cabs for the rest', flavorText: 'Pay for punctuality.', effects: [{ kind: 'money', amount: -140 }, { kind: 'clientXp', amount: 10 }], outcome: 'Everyone arrives annoyed. The take that follows is excellent.' }, 'lon_ts_rework'),
  local('london_music_press', 'london', 'london.press', "LONDON // NEXT WEEK'S COVER", 'A Writer from the Music Press Wants a Studio Visit',
    'A weekly music paper wants five hundred words on your room. They also want a quote about your favourite microphone.',
    { id: 'lon_mp_yes', label: 'Give them the full tour', flavorText: 'Honest, charming, slightly too long.', effects: [{ kind: 'reputation', amount: 5 }], outcome: 'The piece runs under a headline you did not choose.' },
    { id: 'lon_mp_polite', label: 'Politely decline', flavorText: 'Let the records talk.', effects: [{ kind: 'clientXp', amount: 6 }], outcome: 'Your clients like your discretion.' }, 'lon_mp_yes'),
  local('berlin_techno_loan', 'berlin', 'berlin.loan', 'BERLIN // A CABLE LOOM', 'The Club Wants to Borrow Your Speakers',
    'A club three streets over has blown a stack and the headliner lands at midnight. They offer to rent your monitors for a night.',
    { id: 'ber_tl_rent', label: 'Rent them out', flavorText: 'Make them a deal.', effects: [{ kind: 'money', amount: 240 }, { kind: 'gearCondition', amount: -5 }], outcome: 'They come back hot, bass-dusted and perfectly fine.' },
    { id: 'ber_tl_decline', label: 'Say no and keep the room quiet', flavorText: 'Your clients come first.', effects: [{ kind: 'clientXp', amount: 8 }], outcome: 'The promoter respects that and finds a loan elsewhere.' }, 'ber_tl_decline'),
  local('berlin_modular_swap', 'berlin', 'berlin.modular', 'BERLIN // THE RACK IN THE CORNER', 'A Modular Wizard Offers a Swap',
    'A local synth builder with silver rings and no sleep offers a patched-up voice module in exchange for a day of studio time.',
    { id: 'ber_ms_swap', label: 'Take the swap', flavorText: 'Time for sound.', effects: [{ kind: 'gearCondition', amount: 6 }, { kind: 'xp', amount: 40 }], outcome: 'Your studio has a new voice and a few new bruises on the patch bay.' },
    { id: 'ber_ms_cash', label: 'Rent them the room for cash', flavorText: 'Keep it simple.', effects: [{ kind: 'money', amount: 210 }], outcome: 'They bring their own cables and leave them behind.' }, 'ber_ms_cash'),
  local('tokyo_karaoke_night', 'tokyo', 'tokyo.karaoke', 'TOKYO // PRIVATE ROOM 7', 'A Label Throws a Karaoke Night',
    'A label is looking for a backing-track engineer and has booked you a seat at a very long table.',
    { id: 'tok_kn_sing', label: 'Sing one song', flavorText: 'Courage, not talent.', effects: [{ kind: 'reputation', amount: 4 }, { kind: 'clientXp', amount: 8 }], outcome: 'You are terrible. They love you for it.' },
    { id: 'tok_kn_pitch', label: 'Pitch the label instead', flavorText: 'Be the professional in the room.', effects: [{ kind: 'money', amount: 220 }], outcome: 'You leave with a contract and a very strange haircut photo.' }, 'tok_kn_pitch'),
  local('tokyo_earthquake_drill', 'tokyo', 'tokyo.drill', 'TOKYO // 3.2 ON THE SCALE', 'A Small Quake Shakes the Racks',
    'The racks sway and a rack-mount compressor slides a few millimetres off its ears. Nothing falls, but the whole room is thinking about it.',
    { id: 'tok_ed_secure', label: 'Strap down the racks', flavorText: 'Prepare properly.', effects: [{ kind: 'money', amount: -160 }, { kind: 'gearCondition', amount: 5 }], outcome: 'The racks are quiet and a lot more confident.' },
    { id: 'tok_ed_ignore', label: 'Carry on recording', flavorText: 'It was only a small one.', effects: [{ kind: 'gearCondition', amount: -5 }, { kind: 'xp', amount: 20 }], outcome: 'You get a great take and a cracked hinge.' }, 'tok_ed_secure'),
  local('rio_street_party', 'rio', 'rio.street-party', 'RIO // A BLOCK PARTY AT THE DOOR', 'The Street Party Wants Your Console',
    'A block party has set up speakers in the street. They would very much like to wheel your mixing desk out to the pavement.',
    { id: 'rio_sp_lend', label: 'Wheel it out', flavorText: 'Mics in the street, desk on the kerb.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'gearCondition', amount: -6 }], outcome: 'You record the best crowd you have ever heard. The desk smells of caipirinha.' },
    { id: 'rio_sp_mics', label: 'Send two mics and an engineer', flavorText: 'Compromise, with cables.', effects: [{ kind: 'reputation', amount: 3 }, { kind: 'money', amount: 120 }], outcome: 'You get a hundred friends and a clean multitrack.' }, 'rio_sp_mics'),
  local('rio_rainy_season', 'rio', 'rio.rain', 'RIO // THE RAINY SEASON', 'The Roof Starts Singing',
    'The tropical rain finds a hole in the live room roof and starts a rhythm of its own on the snare drum.',
    { id: 'rio_rs_repair', label: 'Patch the roof', flavorText: 'Buckets first, tiles after.', effects: [{ kind: 'money', amount: -200 }, { kind: 'gearCondition', amount: 3 }], outcome: 'Dry, tidy and a little sad.' },
    { id: 'rio_rs_record', label: 'Record the rain as an instrument', flavorText: 'Roll tape, close the window.', effects: [{ kind: 'xp', amount: 50 }, { kind: 'gearCondition', amount: -4 }], outcome: 'It ends up on three records and a ringtone.' }, 'rio_rs_repair'),
  local('detroit_ballroom_echo', 'detroit', 'detroit.ballroom', 'DETROIT // THE BALLROOM FLOOR', 'A Ballroom Offers You the Room After Midnight',
    'The old dance hall is empty after midnight, and its wooden floor turns every snare hit into a second drummer.',
    { id: 'det_be_record', label: 'Move the drums there tonight', flavorText: 'One van, many stairs.', effects: [{ kind: 'xp', amount: 45 }, { kind: 'reputation', amount: 4 }, { kind: 'money', amount: -100 }], outcome: 'The room gives the chorus a backbeat you could not program.' },
    { id: 'det_be_sample', label: 'Capture the room ambience', flavorText: 'Bring the room back to the studio.', effects: [{ kind: 'xp', amount: 25 }, { kind: 'money', amount: 100 }], outcome: 'The room recording is tidy. The caretaker says the real room sounds better.' }, 'det_be_sample'),
  local('detroit_drum_machine', 'detroit', 'detroit.drum-machine', 'DETROIT // A MACHINE FROM A BASEMENT', 'A DJ Brings a Modified Drum Machine',
    'A local DJ has rewired an old rhythm box until the kick rattles the patch bay. They need a clean two-track master by dawn.',
    { id: 'det_dm_master', label: 'Master it loud and clean', flavorText: 'Precision at club volume.', effects: [{ kind: 'money', amount: 220 }, { kind: 'xp', amount: 35 }], outcome: 'At sunrise the loop still sounds like the future.' },
    { id: 'det_dm_trade', label: 'Trade the fee for the modification notes', flavorText: 'Learn the circuit.', effects: [{ kind: 'gearCondition', amount: 6 }, { kind: 'xp', amount: 25 }], outcome: 'Your technician reads the notes twice and reaches for a soldering iron.' }, 'det_dm_master'),
  local('lagos_horn_section', 'lagos', 'lagos.horns', 'LAGOS // ELEVEN HORNS IN RECEPTION', 'A Touring Horn Section Needs a Demo',
    'Eleven players arrive between shows with three arrangements and exactly enough cash for one hour.',
    { id: 'lag_hs_full', label: 'Mic the whole section live', flavorText: 'Clear the room and count them in.', effects: [{ kind: 'reputation', amount: 5 }, { kind: 'xp', amount: 35 }, { kind: 'gearCondition', amount: -2 }], outcome: 'The air in the room moves before the meters do.' },
    { id: 'lag_hs_split', label: 'Record them in smaller groups', flavorText: 'Control the spill.', effects: [{ kind: 'money', amount: 180 }, { kind: 'xp', amount: 20 }], outcome: 'Every note is clean, though the players miss shouting across the room.' }, 'lag_hs_split'),
  local('lagos_radio_jingle', 'lagos', 'lagos.radio', 'LAGOS // LIVE FROM THE RADIO HOUSE', 'A Radio Host Needs a Theme by Evening',
    'A drive-time host wants a new theme before tonight’s show: memorable in five seconds, unmistakably local in ten.',
    { id: 'lag_rj_band', label: 'Bring in a live rhythm section', flavorText: 'Make five seconds feel enormous.', effects: [{ kind: 'money', amount: -80 }, { kind: 'reputation', amount: 5 }, { kind: 'xp', amount: 25 }], outcome: 'By the second broadcast, callers sing it before the host does.' },
    { id: 'lag_rj_keys', label: 'Build it quickly on keys', flavorText: 'Fast, bright, delivered.', effects: [{ kind: 'money', amount: 220 }], outcome: 'The station pays before airtime and asks for three more.' }, 'lag_rj_keys'),
  local('berlin_stranded_truck', 'berlin', 'berlin.truck', 'BERLIN // A TRUCK FULL OF CASES', 'A Tour Truck Breaks Down Outside',
    'A touring band’s truck dies two streets over with a trailer full of flight cases and a show across town in six hours.',
    { id: 'ber_st_store', label: 'Store the cases overnight', flavorText: 'Stack them tight, lock the door.', effects: [{ kind: 'money', amount: 150 }, { kind: 'reputation', amount: 2 }], outcome: 'The crew sleeps on your couch. The cases never leave your sight.' },
    { id: 'ber_st_session', label: 'Lend them the live room', flavorText: 'The show must go somewhere.', effects: [{ kind: 'xp', amount: 40 }, { kind: 'reputation', amount: 4 }, { kind: 'money', amount: -80 }], outcome: 'They play your room like an arena. Your neighbours disagree about the hour.' }, 'ber_st_store'),
  local('tokyo_test_pressing', 'tokyo', 'tokyo.pressing', 'TOKYO // THE LOCKED GROOVE', 'A Test Pressing Skips in the Same Place',
    'The pressing plant sends a test pressing that skips on the same beat every time. The band is divided: flaw or signature?',
    { id: 'tok_tp_recut', label: 'Recut the master', flavorText: 'Fix the groove, keep the take.', effects: [{ kind: 'money', amount: -120 }, { kind: 'xp', amount: 35 }], outcome: 'The new cut plays clean. The band argues about it for a week, then agrees.' },
    { id: 'tok_tp_feature', label: 'Press the skip as a feature', flavorText: 'Sell the mistake.', effects: [{ kind: 'reputation', amount: 4 }, { kind: 'money', amount: 180 }], outcome: 'Collectors hunt the skipping first pressing. The band takes credit for the idea.' }, 'tok_tp_recut'),
];

/**
 * Ultra-rare one-shot city beats (bead 422). Weight 1, single occurrence,
 * tight reputation/money/staff gates — most saves will see only a few.
 * Own family so they never crowd the regular city-local rotation.
 */
export const RARE_CITY_EVENTS: readonly StudioEventDefinition[] = [
  {
    id: 'la_sunset_marquee',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'los-angeles' && f.reputation >= 30,
    narrativeKey: 'city.la.marquee',
    kicker: 'LOS ANGELES // THE NAME ON THE LEASE',
    title: 'A Faded Marquee Star Wants One Song',
    context: () => 'A star whose name used to fill the marquee offers to cut one song incognito — no press, no credit, cash up front.',
    options: [
      opt({ id: 'la_mq_secret', label: 'Record in secret', flavorText: 'Curtains drawn, first names only.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'money', amount: -150 }], outcome: 'Nobody knows. Everybody will hear it in the phrasing of your next three records.' }),
      opt({ id: 'la_mq_comeback', label: 'Bill it as a comeback', flavorText: 'Their name, your room, big type.', effects: [{ kind: 'money', amount: 350 }, { kind: 'reputation', amount: -2 }], outcome: 'The money clears. The mystique does not survive the press release.' }),
    ],
    delegable: true,
    defaultOptionId: 'la_mq_secret',
  },
  {
    id: 'nashville_last_song',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'nashville' && f.reputation >= 25,
    narrativeKey: 'city.nashville.last-song',
    kicker: 'NASHVILLE // THE ENVELOPE FROM THE ESTATE',
    title: 'A Legend’s Unrecorded Last Song',
    context: () => 'An estate lawyer arrives with a sealed envelope: one finished song, never recorded, and instructions to choose the room.',
    options: [
      opt({ id: 'nash_ls_faithful', label: 'Record it faithful', flavorText: 'Not one word changed.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'xp', amount: 40 }], outcome: 'The family weeps in the control room. So do you, a little.' }),
      opt({ id: 'nash_ls_finish', label: 'Finish it your way', flavorText: 'It needs a bridge.', effects: [{ kind: 'money', amount: 300 }, { kind: 'reputation', amount: 1 }], outcome: 'The bridge works. The purists will debate it forever.' }),
    ],
    delegable: true,
    defaultOptionId: 'nash_ls_faithful',
  },
  {
    id: 'london_royalty_audit',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'london' && f.money >= 2000,
    narrativeKey: 'city.london.audit',
    kicker: 'LONDON // THE LETTER WITH THE STAMP',
    title: 'A Royalty Audit Lands on the Desk',
    context: () => 'A publisher claims an old session of yours was sampled without clearance. The letter is polite, expensive, and dated last week.',
    options: [
      opt({ id: 'lon_ra_pay', label: 'Pay the clearance', flavorText: 'Clean books, clean conscience.', effects: [{ kind: 'money', amount: -400 }, { kind: 'reputation', amount: 2 }], outcome: 'It stings. Your paperwork has never been tidier since.' }),
      opt({ id: 'lon_ra_prove', label: 'Dig up the old license', flavorText: 'Somewhere there is paper.', effects: [{ kind: 'xp', amount: 30 }], outcome: 'Three days in the archive finds the signed page. Framed, now.' }),
    ],
    delegable: true,
    defaultOptionId: 'lon_ra_prove',
  },
  {
    id: 'berlin_72_hour_club',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'berlin' && f.staffCount >= 3,
    narrativeKey: 'city.berlin.72-hour',
    kicker: 'BERLIN // SEVENTY-TWO HOURS',
    title: 'A Club Offers a Nonstop Weekend',
    context: () => 'A club wants your crew to run sound for seventy-two unbroken hours. Nobody sleeps. Everybody dances.',
    options: [
      opt({ id: 'ber_72_shifts', label: 'Rotate the whole crew', flavorText: 'Six-hour watches, earplugs mandatory.', effects: [{ kind: 'reputation', amount: 6 }, { kind: 'staffXp', amount: 30 }], outcome: 'Your crew returns deaf, proud, and weirdly better at their jobs.' }),
      opt({ id: 'ber_72_close', label: 'Take only the closing night', flavorText: 'One night, done right.', effects: [{ kind: 'money', amount: 200 }], outcome: 'You play the sunrise set. The rest is someone else’s ringing ears.' }),
    ],
    delegable: true,
    defaultOptionId: 'ber_72_close',
  },
  {
    id: 'tokyo_sumo_choir',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'tokyo' && f.reputation >= 20,
    narrativeKey: 'city.tokyo.sumo',
    kicker: 'TOKYO // THE STABLE SINGS',
    title: 'A Sumo Stable Wants a Ceremonial Song',
    context: () => 'A sumo stable requests a ceremonial song for the new season — forty voices that have never sung together, and one drum.',
    options: [
      opt({ id: 'tok_sc_live', label: 'Record the stable live', flavorText: 'Forty voices, one drum, no click.', effects: [{ kind: 'reputation', amount: 5 }, { kind: 'xp', amount: 35 }], outcome: 'The floor shakes in a way no subwoofer ever has.' }),
      opt({ id: 'tok_sc_stage', label: 'Stage a polished choir', flavorText: 'Pros on the verses, stable on the chorus.', effects: [{ kind: 'money', amount: 280 }], outcome: 'It opens the broadcast. The stable sends salt and thanks.' }),
    ],
    delegable: true,
    defaultOptionId: 'tok_sc_live',
  },
  {
    id: 'rio_carnival_float',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'rio' && f.reputation >= 15,
    narrativeKey: 'city.rio.float',
    kicker: 'RIO // ABOVE THE CROWD',
    title: 'Record Atop a Moving Carnival Float',
    context: () => 'A bloco offers your recorder a seat on their float: eight hours rolling through the crowd, no second passes.',
    options: [
      opt({ id: 'rio_cf_ride', label: 'Ride the float', flavorText: 'Tape rolling, hang on.', effects: [{ kind: 'reputation', amount: 7 }, { kind: 'gearCondition', amount: -6 }], outcome: 'Salt air, swaying mics, and the loudest joy you have ever captured. The recorder needs a service.' }),
      opt({ id: 'rio_cf_curb', label: 'Record from the curb', flavorText: 'Steady feet, clean takes.', effects: [{ kind: 'money', amount: 150 }, { kind: 'xp', amount: 20 }], outcome: 'You catch every bloco as it passes. Your shoes do not survive.' }),
    ],
    delegable: true,
    defaultOptionId: 'rio_cf_curb',
  },
  {
    id: 'detroit_shift_anthem',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'detroit' && f.staffCount >= 2,
    narrativeKey: 'city.detroit.anthem',
    kicker: 'DETROIT // THE WHISTLE BLOWS',
    title: 'An Auto Plant Wants a Shift-Change Anthem',
    context: () => 'The night shift at the plant wants its own anthem for the whistle — recorded with the line still running.',
    options: [
      opt({ id: 'det_sa_live', label: 'Record the line live', flavorText: 'Mics among the machines.', effects: [{ kind: 'xp', amount: 45 }, { kind: 'reputation', amount: 4 }], outcome: 'Hydraulics keep time better than most drummers. The shift adopts it instantly.' }),
      opt({ id: 'det_sa_studio', label: 'Compose it in-studio', flavorText: 'Bring the plant to the booth.', effects: [{ kind: 'money', amount: 250 }], outcome: 'You fake the factory with found sounds. Only the foreman can tell.' }),
    ],
    delegable: true,
    defaultOptionId: 'det_sa_studio',
  },
  {
    id: 'lagos_shrine_session',
    family: 'city-rare',
    baseWeight: 1,
    cooldownDays: 90,
    maxOccurrences: 1,
    eligible: (f) => f.cityId === 'lagos' && f.reputation >= 35,
    narrativeKey: 'city.lagos.shrine',
    kicker: 'LAGOS // THE SHRINE INVITES YOU',
    title: 'An All-Night Shrine Session',
    context: () => 'A legendary shrine venue invites you to record the all-night session — the highest honour the city’s live circuit offers.',
    options: [
      opt({ id: 'lag_ss_accept', label: 'Accept the night', flavorText: 'Dawn comes when it comes.', effects: [{ kind: 'reputation', amount: 8 }, { kind: 'xp', amount: 50 }], outcome: 'At sunrise the crowd carries your monitors to the van. You will talk about this for years.' }),
      opt({ id: 'lag_ss_regrets', label: 'Send regrets with a demo', flavorText: 'Honour it properly, later.', effects: [{ kind: 'money', amount: 200 }], outcome: 'They play your demo between sets. The invitation stays open.' }),
    ],
    delegable: true,
    defaultOptionId: 'lag_ss_regrets',
  },
];
